### ISSUE TITLE
Compass function produces invalid CSS

### ISSUE THREAD

**Issue by kimlindholm** [aniftyco/semantic-ui-sass#3]
Flags don't seem to be working because of this line:

https://github.com/aniftyco/semantic-ui-sass/blob/master/scss/elements/_flag.scss#L34

The culprit is `image-url` Compass function. Should probably be:

```sass
background: url("#{$flags-image-path}/flags.png") no-repeat -108px -1976px;
```

Thanks for a great library btw :)

**Comment by joshmanders** [comment]
Hey @kimlindholm thanks for this report, I gotta get this updated, I'll mark this as to be fixed when I do another release.
