### ISSUE TITLE
No columnCount variable?

### ISSUE THREAD

**Issue by webberwang** [aniftyco/semantic-ui-sass#5]
I'm looking to change the column count from 16 to 12, the variable in less is @columnCount, I'm looking for something like $columnCount but it doesn't seem to exist.

**Comment by joshmanders** [comment]
This module doesn't allow you to change much customization wise.

**Comment by DovahBrownies** [comment]
> Bump

Also looking to change the column count in react from `16` to `12` without editing every single line that has `width: 6.25%`.

**Comment by joshmanders** [comment]
Like I stated, this module just does some simple conversions from LESS to SASS and really doesn't make it very customizable.
